definitions:
  request.LoginStruct:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  request.RegisterStruct:
    properties:
      email:
        type: string
      nickName:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/user/info:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"注册成功"}'
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - Base
  /api/user/login:
    post:
      parameters:
      - description: 用户登录接口
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.LoginStruct'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"注册成功"}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - Base
  /api/user/register:
    post:
      parameters:
      - description: 用户注册接口
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.RegisterStruct'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"注册成功"}'
          schema:
            type: string
      summary: 用户注册账号
      tags:
      - Base
swagger: "2.0"
